-- Migration 002: přidání sloupce kraj + backfill ze CITY_TO_REGION mapy
-- Spusť jednou: psql -U postgres -d realscoreCZ -f 002_add_kraj.sql

ALTER TABLE properties ADD COLUMN IF NOT EXISTS kraj VARCHAR;

CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_properties_kraj
    ON properties (kraj);

-- Backfill: přiřaď kraj dle hodnoty city
UPDATE properties SET kraj = CASE city
    -- Hlavní město Praha
    WHEN 'Praha' THEN 'Hlavní město Praha'
    -- Středočeský kraj
    WHEN 'Kladno' THEN 'Středočeský kraj'
    WHEN 'Mladá Boleslav' THEN 'Středočeský kraj'
    WHEN 'Příbram' THEN 'Středočeský kraj'
    WHEN 'Kolín' THEN 'Středočeský kraj'
    WHEN 'Kutná Hora' THEN 'Středočeský kraj'
    WHEN 'Mělník' THEN 'Středočeský kraj'
    WHEN 'Beroun' THEN 'Středočeský kraj'
    WHEN 'Rakovník' THEN 'Středočeský kraj'
    WHEN 'Benešov' THEN 'Středočeský kraj'
    WHEN 'Nymburk' THEN 'Středočeský kraj'
    WHEN 'Slaný' THEN 'Středočeský kraj'
    WHEN 'Kralupy nad Vltavou' THEN 'Středočeský kraj'
    WHEN 'Brandýs nad Labem-Stará Boleslav' THEN 'Středočeský kraj'
    WHEN 'Brandýs nad Labem' THEN 'Středočeský kraj'
    WHEN 'Neratovice' THEN 'Středočeský kraj'
    WHEN 'Říčany' THEN 'Středočeský kraj'
    WHEN 'Lysá nad Labem' THEN 'Středočeský kraj'
    WHEN 'Poděbrady' THEN 'Středočeský kraj'
    WHEN 'Vlašim' THEN 'Středočeský kraj'
    WHEN 'Sedlčany' THEN 'Středočeský kraj'
    WHEN 'Hořovice' THEN 'Středočeský kraj'
    WHEN 'Dobříš' THEN 'Středočeský kraj'
    WHEN 'Votice' THEN 'Středočeský kraj'
    WHEN 'Mnichovo Hradiště' THEN 'Středočeský kraj'
    WHEN 'Čelákovice' THEN 'Středočeský kraj'
    WHEN 'Roztoky' THEN 'Středočeský kraj'
    WHEN 'Černošice' THEN 'Středočeský kraj'
    WHEN 'Jesenice' THEN 'Středočeský kraj'
    WHEN 'Úvaly' THEN 'Středočeský kraj'
    WHEN 'Benátky nad Jizerou' THEN 'Středočeský kraj'
    WHEN 'Kostelec nad Černými lesy' THEN 'Středočeský kraj'
    WHEN 'Mnichovice' THEN 'Středočeský kraj'
    WHEN 'Čáslav' THEN 'Středočeský kraj'
    WHEN 'Rudná' THEN 'Středočeský kraj'
    WHEN 'Hostivice' THEN 'Středočeský kraj'
    WHEN 'Průhonice' THEN 'Středočeský kraj'
    WHEN 'Vestec' THEN 'Středočeský kraj'
    WHEN 'Tuchoměřice' THEN 'Středočeský kraj'
    WHEN 'Zlonice' THEN 'Středočeský kraj'
    WHEN 'Unhošť' THEN 'Středočeský kraj'
    WHEN 'Nučice' THEN 'Středočeský kraj'
    WHEN 'Čerčany' THEN 'Středočeský kraj'
    WHEN 'Pyšely' THEN 'Středočeský kraj'
    WHEN 'Dobrovice' THEN 'Středočeský kraj'
    WHEN 'Kosmonosy' THEN 'Středočeský kraj'
    WHEN 'Milovice' THEN 'Středočeský kraj'
    WHEN 'Zruč nad Sázavou' THEN 'Středočeský kraj'
    -- Jihočeský kraj
    WHEN 'České Budějovice' THEN 'Jihočeský kraj'
    WHEN 'Písek' THEN 'Jihočeský kraj'
    WHEN 'Tábor' THEN 'Jihočeský kraj'
    WHEN 'Jindřichův Hradec' THEN 'Jihočeský kraj'
    WHEN 'Strakonice' THEN 'Jihočeský kraj'
    WHEN 'Prachatice' THEN 'Jihočeský kraj'
    WHEN 'Kaplice' THEN 'Jihočeský kraj'
    WHEN 'Třeboň' THEN 'Jihočeský kraj'
    WHEN 'Soběslav' THEN 'Jihočeský kraj'
    WHEN 'Blatná' THEN 'Jihočeský kraj'
    WHEN 'Milevsko' THEN 'Jihočeský kraj'
    WHEN 'Vodňany' THEN 'Jihočeský kraj'
    WHEN 'Vimperk' THEN 'Jihočeský kraj'
    WHEN 'Sezimovo Ústí' THEN 'Jihočeský kraj'
    WHEN 'Planá nad Lužnicí' THEN 'Jihočeský kraj'
    WHEN 'Český Krumlov' THEN 'Jihočeský kraj'
    WHEN 'Veselí nad Lužnicí' THEN 'Jihočeský kraj'
    WHEN 'Dačice' THEN 'Jihočeský kraj'
    WHEN 'Týn nad Vltavou' THEN 'Jihočeský kraj'
    WHEN 'Netolice' THEN 'Jihočeský kraj'
    -- Plzeňský kraj
    WHEN 'Plzeň' THEN 'Plzeňský kraj'
    WHEN 'Klatovy' THEN 'Plzeňský kraj'
    WHEN 'Rokycany' THEN 'Plzeňský kraj'
    WHEN 'Domažlice' THEN 'Plzeňský kraj'
    WHEN 'Tachov' THEN 'Plzeňský kraj'
    WHEN 'Horažďovice' THEN 'Plzeňský kraj'
    WHEN 'Nepomuk' THEN 'Plzeňský kraj'
    WHEN 'Stříbro' THEN 'Plzeňský kraj'
    WHEN 'Nýřany' THEN 'Plzeňský kraj'
    WHEN 'Přeštice' THEN 'Plzeňský kraj'
    WHEN 'Stod' THEN 'Plzeňský kraj'
    WHEN 'Dobřany' THEN 'Plzeňský kraj'
    WHEN 'Sušice' THEN 'Plzeňský kraj'
    WHEN 'Kdyně' THEN 'Plzeňský kraj'
    -- Karlovarský kraj
    WHEN 'Karlovy Vary' THEN 'Karlovarský kraj'
    WHEN 'Cheb' THEN 'Karlovarský kraj'
    WHEN 'Sokolov' THEN 'Karlovarský kraj'
    WHEN 'Mariánské Lázně' THEN 'Karlovarský kraj'
    WHEN 'Ostrov' THEN 'Karlovarský kraj'
    WHEN 'Aš' THEN 'Karlovarský kraj'
    WHEN 'Kraslice' THEN 'Karlovarský kraj'
    WHEN 'Chodov' THEN 'Karlovarský kraj'
    WHEN 'Františkovy Lázně' THEN 'Karlovarský kraj'
    WHEN 'Nejdek' THEN 'Karlovarský kraj'
    WHEN 'Loket' THEN 'Karlovarský kraj'
    WHEN 'Horní Slavkov' THEN 'Karlovarský kraj'
    -- Ústecký kraj
    WHEN 'Ústí nad Labem' THEN 'Ústecký kraj'
    WHEN 'Most' THEN 'Ústecký kraj'
    WHEN 'Chomutov' THEN 'Ústecký kraj'
    WHEN 'Teplice' THEN 'Ústecký kraj'
    WHEN 'Děčín' THEN 'Ústecký kraj'
    WHEN 'Litoměřice' THEN 'Ústecký kraj'
    WHEN 'Louny' THEN 'Ústecký kraj'
    WHEN 'Roudnice nad Labem' THEN 'Ústecký kraj'
    WHEN 'Bílina' THEN 'Ústecký kraj'
    WHEN 'Duchcov' THEN 'Ústecký kraj'
    WHEN 'Klášterec nad Ohří' THEN 'Ústecký kraj'
    WHEN 'Litvínov' THEN 'Ústecký kraj'
    WHEN 'Kadaň' THEN 'Ústecký kraj'
    WHEN 'Jirkov' THEN 'Ústecký kraj'
    WHEN 'Žatec' THEN 'Ústecký kraj'
    WHEN 'Varnsdorf' THEN 'Ústecký kraj'
    WHEN 'Rumburk' THEN 'Ústecký kraj'
    WHEN 'Šluknov' THEN 'Ústecký kraj'
    WHEN 'Lovosice' THEN 'Ústecký kraj'
    WHEN 'Podbořany' THEN 'Ústecký kraj'
    WHEN 'Krupka' THEN 'Ústecký kraj'
    WHEN 'Česká Kamenice' THEN 'Ústecký kraj'
    -- Liberecký kraj
    WHEN 'Liberec' THEN 'Liberecký kraj'
    WHEN 'Jablonec nad Nisou' THEN 'Liberecký kraj'
    WHEN 'Česká Lípa' THEN 'Liberecký kraj'
    WHEN 'Semily' THEN 'Liberecký kraj'
    WHEN 'Frýdlant' THEN 'Liberecký kraj'
    WHEN 'Tanvald' THEN 'Liberecký kraj'
    WHEN 'Turnov' THEN 'Liberecký kraj'
    WHEN 'Nový Bor' THEN 'Liberecký kraj'
    WHEN 'Hrádek nad Nisou' THEN 'Liberecký kraj'
    WHEN 'Jilemnice' THEN 'Liberecký kraj'
    WHEN 'Lomnice nad Popelkou' THEN 'Liberecký kraj'
    WHEN 'Železný Brod' THEN 'Liberecký kraj'
    WHEN 'Chrastava' THEN 'Liberecký kraj'
    WHEN 'Doksy' THEN 'Liberecký kraj'
    WHEN 'Mimoň' THEN 'Liberecký kraj'
    WHEN 'Stráž pod Ralskem' THEN 'Liberecký kraj'
    -- Královéhradecký kraj
    WHEN 'Hradec Králové' THEN 'Královéhradecký kraj'
    WHEN 'Náchod' THEN 'Královéhradecký kraj'
    WHEN 'Trutnov' THEN 'Královéhradecký kraj'
    WHEN 'Jičín' THEN 'Královéhradecký kraj'
    WHEN 'Rychnov nad Kněžnou' THEN 'Královéhradecký kraj'
    WHEN 'Dvůr Králové nad Labem' THEN 'Královéhradecký kraj'
    WHEN 'Jaroměř' THEN 'Královéhradecký kraj'
    WHEN 'Nový Bydžov' THEN 'Královéhradecký kraj'
    WHEN 'Hořice' THEN 'Královéhradecký kraj'
    WHEN 'Broumov' THEN 'Královéhradecký kraj'
    WHEN 'Vrchlabí' THEN 'Královéhradecký kraj'
    WHEN 'Police nad Metují' THEN 'Královéhradecký kraj'
    WHEN 'Nová Paka' THEN 'Královéhradecký kraj'
    WHEN 'Dobruška' THEN 'Královéhradecký kraj'
    WHEN 'Kostelec nad Orlicí' THEN 'Královéhradecký kraj'
    WHEN 'Lázně Bělohrad' THEN 'Královéhradecký kraj'
    WHEN 'Hostinné' THEN 'Královéhradecký kraj'
    WHEN 'Špindlerův Mlýn' THEN 'Královéhradecký kraj'
    -- Pardubický kraj
    WHEN 'Pardubice' THEN 'Pardubický kraj'
    WHEN 'Chrudim' THEN 'Pardubický kraj'
    WHEN 'Svitavy' THEN 'Pardubický kraj'
    WHEN 'Ústí nad Orlicí' THEN 'Pardubický kraj'
    WHEN 'Hlinsko' THEN 'Pardubický kraj'
    WHEN 'Polička' THEN 'Pardubický kraj'
    WHEN 'Litomyšl' THEN 'Pardubický kraj'
    WHEN 'Vysoké Mýto' THEN 'Pardubický kraj'
    WHEN 'Lanškroun' THEN 'Pardubický kraj'
    WHEN 'Žamberk' THEN 'Pardubický kraj'
    WHEN 'Přelouč' THEN 'Pardubický kraj'
    WHEN 'Heřmanův Městec' THEN 'Pardubický kraj'
    WHEN 'Moravská Třebová' THEN 'Pardubický kraj'
    WHEN 'Holice' THEN 'Pardubický kraj'
    WHEN 'Česká Třebová' THEN 'Pardubický kraj'
    WHEN 'Sezemice' THEN 'Pardubický kraj'
    -- Kraj Vysočina
    WHEN 'Jihlava' THEN 'Kraj Vysočina'
    WHEN 'Havlíčkův Brod' THEN 'Kraj Vysočina'
    WHEN 'Třebíč' THEN 'Kraj Vysočina'
    WHEN 'Žďár nad Sázavou' THEN 'Kraj Vysočina'
    WHEN 'Pelhřimov' THEN 'Kraj Vysočina'
    WHEN 'Humpolec' THEN 'Kraj Vysočina'
    WHEN 'Velké Meziříčí' THEN 'Kraj Vysočina'
    WHEN 'Bystřice nad Pernštejnem' THEN 'Kraj Vysočina'
    WHEN 'Světlá nad Sázavou' THEN 'Kraj Vysočina'
    WHEN 'Ledeč nad Sázavou' THEN 'Kraj Vysočina'
    WHEN 'Telč' THEN 'Kraj Vysočina'
    WHEN 'Moravské Budějovice' THEN 'Kraj Vysočina'
    WHEN 'Náměšť nad Oslavou' THEN 'Kraj Vysočina'
    WHEN 'Chotěboř' THEN 'Kraj Vysočina'
    WHEN 'Nové Město na Moravě' THEN 'Kraj Vysočina'
    WHEN 'Velká Bíteš' THEN 'Kraj Vysočina'
    WHEN 'Polná' THEN 'Kraj Vysočina'
    WHEN 'Pacov' THEN 'Kraj Vysočina'
    -- Jihomoravský kraj
    WHEN 'Brno' THEN 'Jihomoravský kraj'
    WHEN 'Znojmo' THEN 'Jihomoravský kraj'
    WHEN 'Hodonín' THEN 'Jihomoravský kraj'
    WHEN 'Břeclav' THEN 'Jihomoravský kraj'
    WHEN 'Blansko' THEN 'Jihomoravský kraj'
    WHEN 'Vyškov' THEN 'Jihomoravský kraj'
    WHEN 'Boskovice' THEN 'Jihomoravský kraj'
    WHEN 'Kyjov' THEN 'Jihomoravský kraj'
    WHEN 'Hustopeče' THEN 'Jihomoravský kraj'
    WHEN 'Mikulov' THEN 'Jihomoravský kraj'
    WHEN 'Kuřim' THEN 'Jihomoravský kraj'
    WHEN 'Šlapanice' THEN 'Jihomoravský kraj'
    WHEN 'Modřice' THEN 'Jihomoravský kraj'
    WHEN 'Slavkov u Brna' THEN 'Jihomoravský kraj'
    WHEN 'Rosice' THEN 'Jihomoravský kraj'
    WHEN 'Tišnov' THEN 'Jihomoravský kraj'
    WHEN 'Veselí nad Moravou' THEN 'Jihomoravský kraj'
    WHEN 'Strážnice' THEN 'Jihomoravský kraj'
    WHEN 'Pohořelice' THEN 'Jihomoravský kraj'
    WHEN 'Ivančice' THEN 'Jihomoravský kraj'
    WHEN 'Adamov' THEN 'Jihomoravský kraj'
    WHEN 'Letovice' THEN 'Jihomoravský kraj'
    WHEN 'Valtice' THEN 'Jihomoravský kraj'
    WHEN 'Lednice' THEN 'Jihomoravský kraj'
    WHEN 'Rajhrad' THEN 'Jihomoravský kraj'
    WHEN 'Zastávka' THEN 'Jihomoravský kraj'
    -- Olomoucký kraj
    WHEN 'Olomouc' THEN 'Olomoucký kraj'
    WHEN 'Prostějov' THEN 'Olomoucký kraj'
    WHEN 'Přerov' THEN 'Olomoucký kraj'
    WHEN 'Šumperk' THEN 'Olomoucký kraj'
    WHEN 'Jeseník' THEN 'Olomoucký kraj'
    WHEN 'Uničov' THEN 'Olomoucký kraj'
    WHEN 'Hranice' THEN 'Olomoucký kraj'
    WHEN 'Litovel' THEN 'Olomoucký kraj'
    WHEN 'Konice' THEN 'Olomoucký kraj'
    WHEN 'Mohelnice' THEN 'Olomoucký kraj'
    WHEN 'Zábřeh' THEN 'Olomoucký kraj'
    WHEN 'Šternberk' THEN 'Olomoucký kraj'
    WHEN 'Lipník nad Bečvou' THEN 'Olomoucký kraj'
    WHEN 'Zlaté Hory' THEN 'Olomoucký kraj'
    WHEN 'Hanušovice' THEN 'Olomoucký kraj'
    WHEN 'Velká Bystřice' THEN 'Olomoucký kraj'
    -- Zlínský kraj
    WHEN 'Zlín' THEN 'Zlínský kraj'
    WHEN 'Uherské Hradiště' THEN 'Zlínský kraj'
    WHEN 'Vsetín' THEN 'Zlínský kraj'
    WHEN 'Kroměříž' THEN 'Zlínský kraj'
    WHEN 'Otrokovice' THEN 'Zlínský kraj'
    WHEN 'Uherský Brod' THEN 'Zlínský kraj'
    WHEN 'Vizovice' THEN 'Zlínský kraj'
    WHEN 'Holešov' THEN 'Zlínský kraj'
    WHEN 'Bystřice pod Hostýnem' THEN 'Zlínský kraj'
    WHEN 'Luhačovice' THEN 'Zlínský kraj'
    WHEN 'Valašské Meziříčí' THEN 'Zlínský kraj'
    WHEN 'Rožnov pod Radhoštěm' THEN 'Zlínský kraj'
    WHEN 'Valašské Klobouky' THEN 'Zlínský kraj'
    WHEN 'Slavičín' THEN 'Zlínský kraj'
    WHEN 'Napajedla' THEN 'Zlínský kraj'
    WHEN 'Kunovice' THEN 'Zlínský kraj'
    WHEN 'Staré Město' THEN 'Zlínský kraj'
    WHEN 'Hulín' THEN 'Zlínský kraj'
    -- Moravskoslezský kraj
    WHEN 'Ostrava' THEN 'Moravskoslezský kraj'
    WHEN 'Opava' THEN 'Moravskoslezský kraj'
    WHEN 'Frýdek-Místek' THEN 'Moravskoslezský kraj'
    WHEN 'Karviná' THEN 'Moravskoslezský kraj'
    WHEN 'Havířov' THEN 'Moravskoslezský kraj'
    WHEN 'Orlová' THEN 'Moravskoslezský kraj'
    WHEN 'Bohumín' THEN 'Moravskoslezský kraj'
    WHEN 'Nový Jičín' THEN 'Moravskoslezský kraj'
    WHEN 'Třinec' THEN 'Moravskoslezský kraj'
    WHEN 'Kopřivnice' THEN 'Moravskoslezský kraj'
    WHEN 'Frýdlant nad Ostravicí' THEN 'Moravskoslezský kraj'
    WHEN 'Bruntál' THEN 'Moravskoslezský kraj'
    WHEN 'Krnov' THEN 'Moravskoslezský kraj'
    WHEN 'Frenštát pod Radhoštěm' THEN 'Moravskoslezský kraj'
    WHEN 'Hlučín' THEN 'Moravskoslezský kraj'
    WHEN 'Český Těšín' THEN 'Moravskoslezský kraj'
    WHEN 'Bílovec' THEN 'Moravskoslezský kraj'
    WHEN 'Odry' THEN 'Moravskoslezský kraj'
    WHEN 'Rýmařov' THEN 'Moravskoslezský kraj'
    WHEN 'Příbor' THEN 'Moravskoslezský kraj'
    WHEN 'Studénka' THEN 'Moravskoslezský kraj'
    WHEN 'Klimkovice' THEN 'Moravskoslezský kraj'
    WHEN 'Petřvald' THEN 'Moravskoslezský kraj'
    WHEN 'Rychvald' THEN 'Moravskoslezský kraj'
    WHEN 'Fulnek' THEN 'Moravskoslezský kraj'
    WHEN 'Jablunkov' THEN 'Moravskoslezský kraj'
    ELSE NULL
END
WHERE kraj IS NULL;
